import * as esbuild from 'esbuild'
import { builtinModules } from 'node:module'

const production = process.argv[2] === 'production'

// Preserve compatibility with the Obsidian version declared in manifest.json.
const stripNodeColonPlugin = {
    name: 'strip-node-colon',
    setup({ onResolve }) {
        onResolve({ filter: /^node:/ }, ({ path }) => ({
            path: path.slice('node:'.length),
            external: true,
        }))
    },
}

const options = {
    banner: { js: '/* Generated by esbuild. Source: src/main.ts */' },
    plugins: [stripNodeColonPlugin],
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian', 'electron', ...builtinModules, '@codemirror/*', 'node:*'],
    platform: 'node',
    format: 'cjs',
    target: 'es2016',
    logLevel: 'info',
    loader: {
        '.pegjs': 'text',
        '.js.static': 'text',
        '.svg_content': 'text',
    },
    sourcemap: production ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
}

try {
    if (production) {
        await esbuild.build(options)
    } else {
        const context = await esbuild.context(options)
        const stop = async () => {
            await context.dispose()
            process.exit(0)
        }
        process.once('SIGINT', stop)
        process.once('SIGTERM', stop)
        await context.watch()
    }
} catch (error) {
    console.error(error)
    process.exitCode = 1
}
